[build]
  # Comando para build de produção (arquivos estão na raiz)
  command = "npm run build"
  
  # Diretório onde estão os arquivos compilados
  publish = "build"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Variáveis de ambiente para produção
  REACT_APP_FACEBOOK_APP_ID = "1525902928789947"
  REACT_APP_ENV = "production"

# Redirects para React Router funcionar (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache para assets estáticos
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache para arquivos JS/CSS
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers específicos para meta-callback
[[headers]]
  for = "/meta-callback"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"