[build]
  # Comando para build de produção (ignorando warnings como erros)
  command = "CI=false npm run build"
  
  # Diretório onde estão os arquivos compilados
  publish = "build"
  
  # Diretório das funções serverless
  functions = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Variáveis de ambiente para produção - Supabase
  REACT_APP_SUPABASE_URL = "https://dnamxsapwgltxmtokecd.supabase.co"
  REACT_APP_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuYW14c2Fwd2dsdHhtdG9rZWNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTA2MDQsImV4cCI6MjA3MDIyNjYwNH0.FhdEECAmYkrj78Zs8TI_m2qlZzydw1hYgOr113RPKS8"
  REACT_APP_NAME = "Sheet Tools"
  REACT_APP_DOMAIN = "sheet-tools.com"
  REACT_APP_ENV = "production"
  
  # Variáveis para webhook Shopify (serverless functions)
  SUPABASE_URL = "https://dnamxsapwgltxmtokecd.supabase.co"
  # SUPABASE_SERVICE_ROLE_KEY deve ser configurada no Netlify Dashboard (não aqui por segurança)
  # SHOPIFY_WEBHOOK_SECRET deve ser configurada no Netlify Dashboard (opcional)

# Redirects para React Router funcionar (SPA)
[[redirects]]
  from = "/auth/callback"
  to = "/index.html"
  status = 200

# Funções Netlify são tratadas automaticamente pelo Netlify
# Não precisamos de redirect para /.netlify/functions/*

# Redirect catch-all para SPA (deve vir por último)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache para assets estáticos
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache para arquivos JS/CSS
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

